### ISSUE TITLE
Be able to persists probe state

### ISSUE THREAD

**Issue by MadJlzz** [MadJlzz/madprobe#9]
**Is your feature request related to a problem? Please describe.**
If madprobe is killed, we are unable to restart easily every probe that were running before the shutdown.

**Describe the solution you'd like**
Use a simple and lightweight database to store probe's state and restart every probe if madprobe has restarted.

**Comment by Poivey** [comment]
As discussed, I tried to do solve this issue with boldDB.
https://github.com/MadJlzz/madprobe/pull/11
BoldDB can generate IDs automatically (intergers), so I used this feature and added an ID to the Probe struct. But it seems Probe names are currently unique anyways, should we uses theses names instead of generated ID ? This only work if you think name will stay unique later.

**Comment by MadJlzz** [comment]
Thanks for your participation! 
Indeed, names are unique at the moment. I do not plan to change this behaviour since I found names to be more explicit than IDs in this case.
